name: "coding standards"

on: ["pull_request", "push"]

jobs:
  unit-tests:
    name: "coding standards"

    runs-on: "ubuntu-latest"

    steps:
      - name: "checkout"
        uses: "actions/checkout@v2"

      - name: "installing PHP"
        uses: "shivammathur/setup-php@v2"
        with:
          php-version: "7.4"
          ini-values: memory_limit=-1
          tools: composer:v2, php-cs-fixer, cs2pr

      - name: "checking coding standards"
        run: "php-cs-fixer fix --dry-run --diff --no-ansi"
